### ISSUE TITLE
Final Seminar Presentation

### ISSUE THREAD

**Issue by ancient-sentinel** [ancient-sentinel/UCCS-Social-Robotics#28]
## Description:
Present our Requirements Analysis for the project for the final Senior Seminar presentations.

Presentation Order:
1. Intro - @williamross165 
2. Problem Overview - @williamross165 
3. Problem Background - @williamross165 
4. Standards Discussion - @anguyen7-99 
5. Constraints - @chomuth 
6. Literature Search - @ancient-sentinel 
7. Project Scope - @williamross165 
8. Requirements Analysis: Environment Survey - @chomuth 
9. Requirements Analysis: Customer Needs & Wants - @anguyen7-99 
10. Requirements Analysis: Considerations - @ancient-sentinel 
11. Use Case 1 - @ancient-sentinel 
12. Use Case 2 - @ancient-sentinel 
13. Use Case 3 - @ancient-sentinel 
14. Use Case 4 - @anguyen7-99 
15. Use Case 5 - @chomuth 
16. Use Case 6 - @williamross165 
17. Use Case 7 - @anguyen7-99 
18. Use Case 8 - @ancient-sentinel 
19. Block Diagram - @anguyen7-99 
20. System Design Expectations - @chomuth 
21. Issues - @anguyen7-99 
22. Timeline - @ancient-sentinel 
23. Draft Budget - @williamross165 
24. Conclusion - @chomuth 

## Acceptance Criteria:
* Practiced and well rehearsed delivery
* 20min presentation
* Prepared for 10min of questions

## Deadline:
12/4/2020

**Comment by williamross165** [comment]
Finished.
